### PR TITLE
Make SQLite the default backend

### PR DESCRIPTION
**Pull request by emerkle826**
- minor changes to replace BDBJE with SQLite (v2) as the default backend
- small refactor of SQL statement building inside SQLite Conflict Database impl.
- WorkingTree implementation change to address race/deadlock issues when using SQLite v2 backend
- updating SQLite JDBC driver from 3.8.6 - > 3.8.11.2 due to a bug that causes the JVM to core dump when the SQLite database file resides on an NFS partition
- adding Maven profiles for running/skipping some of the large tests that were previously being skipped with the @Ignore attribute
- removing SQLite V1 implementations

### CODE REVIEW

**Comment by groldan** [comment]
Hi Erik, this is looking good.

A few comments:
- Please squash the commits and make it one, or two if you want, one for all the sqlite work and a separate one for the stress/load tests profile.
- Can we call the profile something like "stressTests" instead of "runLargeNodeTests"?
- We don't mention issue tracker # on commit messages. Not even if using github issues. Rationale being that during the project lifetime the issue tracker may change (it actually happens more often than desired, and int this particular case it isn't even publicly accessible). Instead, the project's policy (tm) is to use compact subject line followed by a blank line and then one or two paragraphs explaining the change in a way that complements the code diff (i.e. no unnecessary detail, but high level motivation or whatever seems appropriate)

**Comment by groldan** [comment]
One other thing: we should move the {{org.xerial}} dependency declaration with its version number to the root pom's {{dependencyManagement}} section, and include it only the groupId and artifactId in the storage/sqlite/xerial module. If you can also do that that'd be appreciated.
Cheers.

**Comment by emerkle826** [comment]
@groldan Will do.

**Comment by emerkle826** [comment]
@groldan don't merge this yet. Apparently there is an issue with the Stress tests when I run them on my MBP. I've been running them on my desktop (which isn't quite as powerful) and haven't seen the issues. Running them on the Mac is revealing an issue, possible a race condition my desktop isn't able to trigger.

I'll keep digging on this and let you know when I get it resolved.

**Pull request closed without merging**
